# Generated by Django 2.2 on 2019-12-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.ManyToManyField(related_name='wishes_liked', to='app_one.User'),
        ),
    ]
